In [ ]:
import numpy as np


def are_vectors_linearly_independent(vectors):
    matrix = np.array(vectors).T
    print(matrix)

    rank_matrix = np.linalg.matrix_rank(matrix)
    print(rank_matrix)

    return rank_matrix == len(vectors)


# Приклад використання
vectors1 = np.array([1, 2, 3])
vectors2 = np.array([-2, 1, -1])
vectors3 = np.array([3, 2, -1])

# Приклад використання
# vectors1 = np.array([1, 2, -3])
# vectors2 = np.array([-1, 2, 4])
# vectors3 = np.array([1, 6, -2])

result = are_vectors_linearly_independent([vectors1, vectors2, vectors3])

if result:
    print("Вектори лінійно незалежні.")
else:
    print("Вектори лінійно залежні.")

[[ 1 -2  3]
 [ 2  1  2]
 [ 3 -1 -1]]
3
Вектори лінійно незалежні.
